name: Deploy

on:
  push:
      branches:
      - pages

concurrency:
   group: deploy
   cancel-in-progress: true

env:
  NODE_VERSION: 16

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Deploy
      run: pnpm build
    - name: Copy
      run: |-
        mkdir -p docs/
        cp dist/* docs/ -r
